force-app/main/default/objects/Case_Note__c/Case_Note__c.object-meta.xml
<CustomObject>
    <description>this custom object will be used to replicate Tasks and Activities since CC portal users cannot use the standard functionality</description>
    <label>Case Note</label>
    <nameField>
        <displayFormat>CN-{MM}{YY}-{0}</displayFormat>
        <label>Case Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Note__c/fields/Communication_Date__c.field-meta.xml
<CustomField>
    <fullName>Communication_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>Allows user to specify when the communication occurred. Defaults to today.</description>
    <inlineHelpText>Manually specify the date when the communication occurred</inlineHelpText>
    <label>Communication Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case_Note__c/fields/Communication_Result__c.field-meta.xml
<CustomField>
    <fullName>Communication_Result__c</fullName>
    <label>Communication Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>need values</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Note__c/fields/Intervention_Type__c.field-meta.xml
<CustomField>
    <fullName>Intervention_Type__c</fullName>
    <label>Intervention Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Resource Navigation</fullName>
            </value>
            <value>
                <fullName>Career Coaching</fullName>
            </value>
            <value>
                <fullName>Academic Advising</fullName>
            </value>
            <value>
                <fullName>Mental Health Support</fullName>
            </value>
            <value>
                <fullName>Outreach</fullName>
                <isActive>false</isActive>
                <label>Outreach</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Note__c/fields/Related_To_Contact__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Contact object</description>
    <label>Related To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Case Notes</relationshipLabel>
    <relationshipName>Case_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Note__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
            <value>
                <fullName>Outbound Call</fullName>
            </value>
            <value>
                <fullName>In Person</fullName>
            </value>
            <value>
                <fullName>Inbound Email</fullName>
            </value>
            <value>
                <fullName>Outbound Email</fullName>
            </value>
            <value>
                <fullName>Mail</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseNotes.cls
public with sharing class CaseNotes {
	@AuraEnabled
	public static List<Case_Note__c> getCaseNotes(Id contactId) {
		return [
			SELECT
				Id,
				Communication_Date__c,
				Communication_Result__c,
				Intervention_Type__c,
				Type__c,
				Comments__c,
				CreatedDate,
				CreatedBy.Name
			FROM Case_Note__c
			WHERE Related_To_Contact__c = :contactId
			ORDER BY Communication_Date__c
		];
	}

	@AuraEnabled
	public static Case_Note__c createCaseNote(Case_Note__c note) {
		insert note;
		return note;
	}
}